"""Networking service — DuckDB-backed contact CRUD + Ollama outreach suggestions.

Contacts stored in ``~/.dex-studio/careerdex/networking.duckdb``.
Outreach suggestions generated by local Ollama (graceful fallback when offline).
"""

from __future__ import annotations

import json
import re
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import duckdb
import structlog

from careerdex.models.networking import (
    ContactRelationship,
    Interaction,
    NetworkContact,
)

logger = structlog.get_logger()

__all__ = ["NetworkingService"]

_DEFAULT_DB_PATH = Path.home() / ".dex-studio" / "careerdex" / "networking.duckdb"

_CREATE_TABLE = """
CREATE TABLE IF NOT EXISTS contacts (
    id                VARCHAR PRIMARY KEY,
    name              VARCHAR NOT NULL,
    title             VARCHAR DEFAULT '',
    company           VARCHAR DEFAULT '',
    email             VARCHAR DEFAULT '',
    linkedin_url      VARCHAR DEFAULT '',
    relationship      VARCHAR DEFAULT 'other',
    tags_json         VARCHAR DEFAULT '[]',
    notes             VARCHAR DEFAULT '',
    interactions_json VARCHAR DEFAULT '[]',
    next_follow_up    TIMESTAMP,
    application_id    VARCHAR DEFAULT '',
    created_at        TIMESTAMP NOT NULL,
    updated_at        TIMESTAMP NOT NULL
);
"""

_OLLAMA_URL = "http://localhost:11434/api/generate"
_OLLAMA_MODEL = "llama3.2"

_OUTREACH_PROMPT = """\
You are a career coach helping someone write a professional outreach message.

Contact: {name}, {title} at {company}
Relationship: {relationship}
Context/notes: {notes}
Goal: {goal}

Write a concise, genuine outreach message (3-4 sentences max). No generic filler.
Return exactly this JSON (no markdown):
{{
  "subject": "<email/LinkedIn subject line>",
  "message": "<the outreach message>",
  "tips": ["<tip 1>", "<tip 2>"]
}}
"""


class NetworkingService:
    """DuckDB-backed networking contacts + Ollama-powered outreach drafts.

    Usage::

        svc = NetworkingService()
        contact = svc.add(NetworkContact(name="Alice", company="Acme"))
        svc.log_interaction(contact.id, Interaction(type=InteractionType.CALL, note="..."))
        draft = svc.suggest_outreach(contact, goal="referral for SWE role")
        svc.close()
    """

    def __init__(self, db_path: Path | None = None) -> None:
        self._db_path = db_path or _DEFAULT_DB_PATH
        self._db_path.parent.mkdir(parents=True, exist_ok=True)
        self._conn = duckdb.connect(str(self._db_path))
        self._conn.execute(_CREATE_TABLE)

    def close(self) -> None:
        self._conn.close()

    # -- CRUD ----------------------------------------------------------------

    def add(self, contact: NetworkContact) -> NetworkContact:
        self._conn.execute(
            """
            INSERT INTO contacts (
                id, name, title, company, email, linkedin_url,
                relationship, tags_json, notes, interactions_json,
                next_follow_up, application_id, created_at, updated_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            [
                contact.id,
                contact.name,
                contact.title,
                contact.company,
                contact.email,
                contact.linkedin_url,
                contact.relationship.value,
                json.dumps(contact.tags),
                contact.notes,
                json.dumps([i.model_dump(mode="json") for i in contact.interactions]),
                contact.next_follow_up.isoformat() if contact.next_follow_up else None,
                contact.application_id,
                contact.created_at.isoformat(),
                contact.updated_at.isoformat(),
            ],
        )
        logger.info("contact_added", id=contact.id, name=contact.name)
        return contact

    def get(self, contact_id: str) -> NetworkContact | None:
        row = self._conn.execute("SELECT * FROM contacts WHERE id = ?", [contact_id]).fetchone()
        return self._row_to_contact(row) if row else None

    def list_all(self, search: str = "") -> list[NetworkContact]:
        if search:
            term = f"%{search.lower()}%"
            rows = self._conn.execute(
                "SELECT * FROM contacts WHERE LOWER(name) LIKE ? OR LOWER(company) LIKE ?"
                " ORDER BY updated_at DESC",
                [term, term],
            ).fetchall()
        else:
            rows = self._conn.execute("SELECT * FROM contacts ORDER BY updated_at DESC").fetchall()
        return [self._row_to_contact(r) for r in rows]

    def update(self, contact: NetworkContact) -> None:
        contact.updated_at = datetime.now(UTC)
        self._conn.execute(
            """
            UPDATE contacts SET
                name = ?, title = ?, company = ?, email = ?, linkedin_url = ?,
                relationship = ?, tags_json = ?, notes = ?, interactions_json = ?,
                next_follow_up = ?, application_id = ?, updated_at = ?
            WHERE id = ?
            """,
            [
                contact.name,
                contact.title,
                contact.company,
                contact.email,
                contact.linkedin_url,
                contact.relationship.value,
                json.dumps(contact.tags),
                contact.notes,
                json.dumps([i.model_dump(mode="json") for i in contact.interactions]),
                contact.next_follow_up.isoformat() if contact.next_follow_up else None,
                contact.application_id,
                contact.updated_at.isoformat(),
                contact.id,
            ],
        )

    def delete(self, contact_id: str) -> bool:
        existing = self.get(contact_id)
        if existing is None:
            return False
        self._conn.execute("DELETE FROM contacts WHERE id = ?", [contact_id])
        logger.info("contact_deleted", id=contact_id)
        return True

    def log_interaction(
        self,
        contact_id: str,
        interaction: Interaction,
    ) -> NetworkContact | None:
        """Append an interaction to a contact's history."""
        contact = self.get(contact_id)
        if contact is None:
            return None
        contact.interactions.append(interaction)
        contact.updated_at = datetime.now(UTC)
        self.update(contact)
        logger.info("interaction_logged", contact_id=contact_id, type=interaction.type)
        return contact

    def due_follow_ups(self) -> list[NetworkContact]:
        """Return contacts with next_follow_up <= now."""
        now = datetime.now(UTC).isoformat()
        rows = self._conn.execute(
            "SELECT * FROM contacts WHERE next_follow_up IS NOT NULL"
            " AND next_follow_up <= ? ORDER BY next_follow_up ASC",
            [now],
        ).fetchall()
        return [self._row_to_contact(r) for r in rows]

    def stats(self) -> dict[str, int]:
        """Return counts: total, by relationship, due follow-ups."""
        total = self._conn.execute("SELECT COUNT(*) FROM contacts").fetchone()
        by_rel = self._conn.execute(
            "SELECT relationship, COUNT(*) FROM contacts GROUP BY relationship"
        ).fetchall()
        now = datetime.now(UTC).isoformat()
        due = self._conn.execute(
            "SELECT COUNT(*) FROM contacts WHERE next_follow_up IS NOT NULL"
            " AND next_follow_up <= ?",
            [now],
        ).fetchone()
        result: dict[str, int] = {"total": total[0] if total else 0}
        for rel, count in by_rel:
            result[str(rel)] = int(count)
        result["due_follow_ups"] = due[0] if due else 0
        return result

    # -- Ollama outreach -----------------------------------------------------

    def suggest_outreach(
        self,
        contact: NetworkContact,
        goal: str = "connect and learn about opportunities",
    ) -> dict[str, Any]:
        """Generate an outreach message via local Ollama.

        Returns dict with 'subject', 'message', 'tips'.
        Raises RuntimeError if Ollama is unreachable.
        """
        import httpx

        prompt = _OUTREACH_PROMPT.format(
            name=contact.name,
            title=contact.title or "professional",
            company=contact.company or "their company",
            relationship=contact.relationship.value.replace("_", " "),
            notes=contact.notes[:300] if contact.notes else "none",
            goal=goal,
        )

        try:
            resp = httpx.post(
                _OLLAMA_URL,
                json={"model": _OLLAMA_MODEL, "prompt": prompt, "stream": False},
                timeout=60.0,
            )
            resp.raise_for_status()
            raw = resp.json().get("response", "")
            # Strip markdown fences if model wraps in ```json
            raw = re.sub(r"```(?:json)?", "", raw).strip()
            result: dict[str, Any] = json.loads(raw)
            logger.info("outreach_generated", contact_id=contact.id)
            return result
        except Exception as exc:
            logger.warning("outreach_generation_failed", error=str(exc))
            raise RuntimeError(f"Ollama unavailable: {exc}") from exc

    # -- private -------------------------------------------------------------

    def _row_to_contact(self, row: tuple[object, ...]) -> NetworkContact:
        (
            id_,
            name,
            title,
            company,
            email,
            linkedin_url,
            relationship,
            tags_json,
            notes,
            interactions_json,
            next_follow_up,
            application_id,
            created_at,
            updated_at,
        ) = row

        interactions: list[Interaction] = []
        try:
            for d in json.loads(str(interactions_json or "[]")):
                interactions.append(Interaction(**d))
        except (json.JSONDecodeError, TypeError):
            pass

        try:
            tags: list[str] = json.loads(str(tags_json or "[]"))
        except (json.JSONDecodeError, TypeError):
            tags = []

        return NetworkContact(
            id=str(id_),
            name=str(name),
            title=str(title or ""),
            company=str(company or ""),
            email=str(email or ""),
            linkedin_url=str(linkedin_url or ""),
            relationship=ContactRelationship(str(relationship or "other")),
            tags=tags,
            notes=str(notes or ""),
            interactions=interactions,
            next_follow_up=_parse_dt(next_follow_up),
            application_id=str(application_id or ""),
            created_at=_parse_dt(created_at) or datetime.now(UTC),
            updated_at=_parse_dt(updated_at) or datetime.now(UTC),
        )


def _parse_dt(value: object) -> datetime | None:
    if value is None:
        return None
    if isinstance(value, datetime):
        return value if value.tzinfo else value.replace(tzinfo=UTC)
    try:
        dt = datetime.fromisoformat(str(value))
        return dt if dt.tzinfo else dt.replace(tzinfo=UTC)
    except ValueError:
        return None
