name: Auto PR

on:
  push:
    branches:
      - '*'

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  auto-pr:
    if: github.ref_name != 'main'
    uses: TheDataEngineX/.github/.github/workflows/reusable-auto-pr-to-main.yml@main
    secrets: inherit
