name: Auto PR

on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  feature-to-main:
    if: startsWith(github.ref, 'refs/heads/feature/') || startsWith(github.ref, 'refs/heads/fix/')
    uses: TheDataEngineX/.github/.github/workflows/auto-pr-to-main.yml@main
    secrets: inherit
